# -*- coding: utf-8 -*-
"""Lab 11: Class trong Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15CHkTU8q-XQy3zHLpr1BaFgb4zdnKYmZ

# Lab 11: Class trong Python

Ở bài Lab này, bạn sẽ cần hoàn thành các đoạn code ở phần `[...]` để hoàn thiện bài toán theo yêu cầu từ đề bài.

## Lab 11.1

**Đề bài** : Tạo một Class `Bike` bao gồm hai thuộc tính như sau
- `color (string)`: Màu sắc của chiếc xe.
- `price (float)`: Giá của chiếc xe.


Sau đó, tạo hai Object Bike là `testOne (color = 'blue', price = 89.99)` và `testTwo (color = 'purple', price = 25.0)`.
"""

class Bike:
  color = ""
  price = 0.0
  def __init__(self, color , price) -> None:
    self.color = color
    self.price = price

testOne = Bike(color = 'blue', price = 89.99)
testTwo = Bike(color = 'purple', price = 25.0)

"""Kiểm tra xem đoạn code đã hoạt động đúng chưa, nếu như output như sau thì bạn đã hoàn thành bài Lab này: 
```
blue 89.99
purple 25.0
```
"""

print(testOne.color, testOne.price)
print(testTwo.color, testTwo.price)

"""## Lab 11.2

**Đề bài** : Tạo một Class `AppleBasket` bao gồm hai thuộc tính như sau
- `apple_color (string)`: Màu sắc của quả táo.
- `apple_quantity (int)`: Số lượng táo trong giỏ.


Sau đó, bạn cần tạo một Class Method `increase` sử dụng để tăng giá trị của thuộc tính apple_quantity` thêm 1.

Cuối dùng, bạn cần thiết kế để khi in Object được tạo thì sẽ có format như sau `A basket of [quantity] [color] apples.`
"""

class AppleBasket:
  apple_color = ""
  apple_quantity  = 0
  def __init__(self, apple_color , apple_quantity) -> None:
    self.color = apple_color
    self.price = apple_quantity
  def increase(self):
    self.apple_quantity += 1
  def __str__(self) -> str:
    return "A basket of " + str(self.apple_quantity) + str(self.apple_color) + " apples."

"""Kiểm tra xem đoạn code đã hoạt động đúng chưa, nếu như output như sau thì bạn đã hoàn thành bài Lab này: 
```
A basket of 4 red apples.
A basket of 5 red apples.
```
"""

testOne = AppleBasket('red',4)
print(testOne)
testOne.increase()
print(testOne)