# -*- coding: utf-8 -*-
"""Lab 16: Xử lý Exception.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUTOSq5e8OTPmbAbfYTGmnu4hnzlCl4x

# Lab 16: Xử lý Exception

Ở bài Lab này, bạn sẽ cần hoàn thành các đoạn code ở phần `[...]` để hoàn thiện bài toán theo yêu cầu từ đề bài.

## Lab 16.1

**Đề bài** : Ở bài toán dưới đây, bạn được cung cấp danh sách các quốc gia ở mảng `country` và danh sách số lương huy chương vàng của từng quốc gia. Bạn cần hoàn thành đoạn code để lấy danh sách huy chương vàng theo các quốc gia ở mảng `country`, nếu như không có dữ liệu ở biến `gold` thì hãy trả về  `"Did not get gold"`. Ví dụ như sau:
```
gold = {"US": 46, "Fiji": 1, "Great Britain": 27, "Cuba": 5, "Thailand": 2, "China": 26, "France": 10}
country = ["Fiji", "Chile", "Mexico", "France", "Norway", "US"]
```
Thì kết quả sẽ là:
```
[1, 'Did not get gold', 'Did not get gold', 10, 'Did not get gold', 46]
```
"""

gold = {"US": 46, "Fiji": 1, "Great Britain": 27, "Cuba": 5, "Thailand": 2, "China": 26, "France": 10}
country = ["Fiji", "Chile", "Mexico", "France", "Norway", "US"]
country_gold = []

for x in country:
    try:
      country_gold.append(gold[x])
    except:
      country_gold.append('Did not get gold')

print(country_gold)

"""## Lab 16.2

**Đề bài** : Ở bài tập này, bạn sẽ cần lọc các số ở mảng `lst` để tìm các số là ước số của 100. Ví dụ: 
```
[2, 4, 10, 42, 12, 0, 4, 7, 21, 4, 83, 8, 5, 6, 8, 234, 5, 6, 523, 42, 34, 0, 234, 1, 435, 465, 56, 7, 3, 43, 23]
```
Thì kết quả sẽ là:
```
[2, 4, 10, 4, 4, 5, 5, 1]
```
"""

lst = [2, 4, 10, 42, 12, 0, 4, 7, 21, 4, 83, 8, 5, 6, 8, 234, 5, 6, 523, 42, 34, 0, 234, 1, 435, 465, 56, 7, 3, 43, 23]

lst_three = []

for num in lst:
    try:
      if (100 % num == 0):
        lst_three.append(num)
    except:
        pass
print(lst_three)